const nomesSimples = [
  "Adriana", "Afonso", "Alana", "Alex", "Alice", "Almir", "Amanda", "Amélia", 
  "Ana", "André", "Antônio", "Ariadne", "Arthur", "Beatriz", "Bento", "Breno", 
  "Bruna", "Bruno", "Caio", "Camila", "Carla", "Carlos", "Catarina", "Cecília", 
  "Celso", "César", "Clarice", "Cláudia", "Cleo", "Cristiano", "Daniel", 
  "Davi", "Débora", "Denise", "Diego", "Diogo", "Douglas", "Eduardo", 
  "Elisa", "Eliane", "Elias", "Emanuel", "Emily", "Enzo", "Eric", "Estela", 
  "Eugênio", "Fabiana", "Fábio", "Fernanda", "Fernando", "Flávia", "Flávio", 
  "Gabriel", "Gabriela", "Geraldo", "Giovana", "Gisele", "Guilherme", 
  "Gustavo", "Heitor", "Helena", "Henrique", "Hugo", "Igor", "Ingrid", 
  "Isabel", "Isabela", "Ivan", "Jéssica", "João", "Joaquim", "Jorge", 
  "José", "Júlia", "Juliana", "Júnior", "Karen", "Karina", "Larissa", 
  "Laura", "Leandro", "Leda", "Leonardo", "Letícia", "Lígia", "Lilian", 
  "Lorena", "Lucas", "Luís", "Luísa", "Manoel", "Marcela", "Marcelo", 
  "Márcia", "Mário", "Mariana", "Marina", "Marta", "Matheus", "Miguel", 
  "Milena", "Miriam", "Natália", "Nelson", "Nicole", "Nicolas", "Olga", 
  "Otávio", "Paulo", "Pedro", "Priscila", "Rafael", "Rafaela", "Raquel", 
  "Rebeca", "Renata", "Renato", "Ricardo", "Rodrigo", "Rogério", "Samuel", 
  "Sandra", "Sandro", "Sara", "Sérgio", "Simone", "Sofia", "Suzana", "Tadeu", 
  "Talita", "Tatiana", "Thaís", "Tiago", "Valéria", "Vera", "Vicente", 
  "Vinícius", "Vitor", "Vítor", "Viviane", "Wagner", "Wesley", "William", 
  "Yago", "Yasmin", "Yuri", "Zilda", "Zuleica"
];

const nomesCompostos = [
  "Ana Beatriz", "Ana Carolina", "Ana Clara", "Ana Júlia", "Ana Laura", 
  "Ana Luísa", "Ana Maria", "Ana Paula", "Ana Vitória", "André Luiz", 
  "Antônio Carlos", "Arthur Henrique", "Bruno César", "Caio Henrique", 
  "Carlos Alberto", "Carlos Eduardo", "Daniel Henrique", "Daniela Cristina", 
  "Eduardo Felipe", "Eduardo Henrique", "Enzo Gabriel", "Enzo Miguel", 
  "Felipe Augusto", "Felipe Eduardo", "Felipe Henrique", "Fernanda Cristina", 
  "Fernanda Maria", "Gabriel Henrique", "Gabriela Cristina", "Giovana Maria", 
  "Guilherme Augusto", "Guilherme Henrique", "Heitor Gabriel", "Isabel Cristina", 
  "Isabel Maria", "Isabela Fernanda", "João Antônio", "João Gabriel", 
  "João Guilherme", "João Lucas", "João Miguel", "João Pedro", "João Vitor", 
  "José Antônio", "José Carlos", "José Eduardo", "José Henrique", "José Luiz", 
  "José Maria", "José Pedro", "Júlia Maria", "Juliana Cristina", "Larissa Cristina", 
  "Laura Beatriz", "Laura Maria", "Leonardo Augusto", "Leonardo Henrique", 
  "Lívia Gabriela", "Lucas Gabriel", "Lucas Henrique", "Luís Augusto", 
  "Luís Felipe", "Luís Gustavo", "Luís Henrique", "Luísa Gabriela", 
  "Maria Alice", "Maria Antônia", "Maria Beatriz", "Maria Clara", 
  "Maria Eduarda", "Maria Fernanda", "Maria Flor", "Maria Gabriela", 
  "Maria Isabel", "Maria Júlia", "Maria Laura", "Maria Luísa", "Maria Vitória", 
  "Mariana Cristina", "Matheus Gabriel", "Matheus Henrique", "Miguel Ângelo", 
  "Nathália Cristina", "Natália Maria", "Nicole Beatriz", "Nicole Cristina", 
  "Otávio Augusto", "Otávio Henrique", "Paula Fernanda", "Paula Maria", 
  "Paulo Henrique", "Pedro Antônio", "Pedro Augusto", "Pedro Henrique", 
  "Pedro Lucas", "Pedro Miguel", "Pedro Vitor", "Rafael Augusto", 
  "Rafael Henrique", "Rafaela Cristina", "Renata Beatriz", "Renata Cristina", 
  "Ricardo Henrique", "Rodrigo Antônio", "Rodrigo Augusto", "Rodrigo Henrique", 
  "Sabrina Cristina", "Sara Maria", "Sérgio Ricardo", "Sofia Beatriz", 
  "Sofia Gabriela", "Tatiana Maria", "Tiago Henrique", "Valéria Cristina", 
  "Vitor Gabriel", "Vitor Henrique", "Wagner Luiz", "Wesley Henrique", 
  "William Henrique", "Yasmin Gabriela", "Yasmin Maria", "Yuri Gabriel", 
  "Yuri Henrique"
];

const nomes = [
  "Adriana", "Afonso", "Alana", "Alex", "Alice", "Almir", "Amanda", "Amélia", 
  "Ana", "Ana Beatriz", "Ana Carolina", "Ana Clara", "Ana Júlia", "Ana Laura", 
  "Ana Luísa", "Ana Maria", "Ana Paula", "Ana Vitória", "André", "André Luiz", 
  "Antônio", "Antônio Carlos", "Ariadne", "Arthur", "Arthur Henrique", "Beatriz", 
  "Bento", "Breno", "Bruna", "Bruno", "Bruno César", "Caio", "Caio Henrique", 
  "Camila", "Carla", "Carlos", "Carlos Alberto", "Carlos Eduardo", "Catarina", 
  "Cecília", "Celso", "César", "Clarice", "Cláudia", "Cleo", "Cristiano", 
  "Daniel", "Daniel Henrique", "Davi", "Débora", "Denise", "Diego", "Diogo", 
  "Douglas", "Eduardo", "Eduardo Felipe", "Eduardo Henrique", "Elisa", "Eliane", 
  "Elias", "Emanuel", "Emily", "Enzo", "Enzo Gabriel", "Enzo Miguel", "Eric", 
  "Estela", "Eugênio", "Fabiana", "Fábio", "Felipe", "Felipe Augusto", 
  "Felipe Eduardo", "Felipe Henrique", "Fernanda", "Fernanda Cristina", 
  "Fernanda Maria", "Fernando", "Flávia", "Flávio", "Gabriel", "Gabriel Henrique", 
  "Gabriela", "Gabriela Cristina", "Geraldo", "Giovana", "Giovana Maria", 
  "Gisele", "Guilherme", "Guilherme Augusto", "Guilherme Henrique", "Gustavo", 
  "Heitor", "Heitor Gabriel", "Helena", "Henrique", "Hugo", "Igor", "Ingrid", 
  "Isabel", "Isabel Cristina", "Isabel Maria", "Isabela", "Isabela Fernanda", 
  "Ivan", "Jéssica", "João", "João Antônio", "João Gabriel", "João Guilherme", 
  "João Lucas", "João Miguel", "João Pedro", "João Vitor", "Joaquim", "Jorge", 
  "José", "José Antônio", "José Carlos", "José Eduardo", "José Henrique", 
  "José Luiz", "José Maria", "José Pedro", "Júlia", "Júlia Maria", "Juliana", 
  "Juliana Cristina", "Júnior", "Karen", "Karina", "Larissa", "Larissa Cristina", 
  "Laura", "Laura Beatriz", "Laura Maria", "Leandro", "Leda", "Leonardo", 
  "Leonardo Augusto", "Leonardo Henrique", "Letícia", "Lígia", "Lilian", 
  "Lorena", "Lucas", "Lucas Gabriel", "Lucas Henrique", "Luís", "Luís Augusto", 
  "Luís Felipe", "Luís Gustavo", "Luís Henrique", "Luísa", "Luísa Gabriela", 
  "Manoel", "Marcela", "Marcelo", "Márcia", "Maria Alice", "Maria Antônia", 
  "Maria Beatriz", "Maria Clara", "Maria Eduarda", "Maria Fernanda", "Maria Flor", 
  "Maria Gabriela", "Maria Isabel", "Maria Júlia", "Maria Laura", "Maria Luísa", 
  "Maria Vitória", "Mariana", "Mariana Cristina", "Marina", "Marta", "Matheus", 
  "Matheus Gabriel", "Matheus Henrique", "Miguel", "Miguel Ângelo", "Milena", 
  "Miriam", "Natália", "Nathália Cristina", "Natália Maria", "Nelson", "Nicole", 
  "Nicole Beatriz", "Nicole Cristina", "Nicolas", "Olga", "Otávio", "Otávio Augusto", 
  "Otávio Henrique", "Paula", "Paula Fernanda", "Paula Maria", "Paulo", 
  "Paulo Henrique", "Pedro", "Pedro Antônio", "Pedro Augusto", "Pedro Henrique", 
  "Pedro Lucas", "Pedro Miguel", "Pedro Vitor", "Priscila", "Rafael", 
  "Rafael Augusto", "Rafael Henrique", "Rafaela", "Rafaela Cristina", "Raquel", 
  "Rebeca", "Renata", "Renata Beatriz", "Renata Cristina", "Renato", "Ricardo", 
  "Ricardo Henrique", "Rodrigo", "Rodrigo Antônio", "Rodrigo Augusto", 
  "Rodrigo Henrique", "Rogério", "Samuel", "Sandra", "Sandro", "Sabrina", 
  "Sabrina Cristina", "Sara", "Sara Maria", "Sérgio", "Sérgio Ricardo", "Simone", 
  "Sofia", "Sofia Beatriz", "Sofia Gabriela", "Suzana", "Tadeu", "Talita", 
  "Tatiana", "Tatiana Maria", "Thaís", "Tiago", "Tiago Henrique", "Ulisses", 
  "Ursula", "Valéria", "Valéria Cristina", "Vera", "Vicente", "Vinícius", 
  "Vitor", "Vítor Gabriel", "Vítor Henrique", "Viviane", "Wagner", "Wagner Luiz", 
  "Wesley", "Wesley Henrique", "William", "William Henrique", "Yago", 
  "Yasmin", "Yasmin Gabriela", "Yasmin Maria", "Yuri", "Yuri Gabriel", 
  "Yuri Henrique", "Zilda", "Zuleica"
];

const numeros = [
  3, 7, 12, 18, 23, 27, 32, 36, 41, 45, 50, 54, 60, 65, 70, 75, 80, 85, 
  90, 95, 100, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 
  165, 170, 175, 180, 185, 190, 195, 200, 206, 211, 216, 221, 226, 231, 236, 
  241, 246, 251, 256, 261, 266, 271, 276, 281, 286, 291, 296, 301, 306, 311, 
  316, 321, 326, 331, 336, 341, 346, 351, 356, 361, 366, 371, 376, 381, 386, 
  391, 396, 401, 406, 411, 416, 421, 426, 431, 436, 441, 446, 451, 456, 461, 
  466, 471, 476, 481, 486, 491, 496, 501, 506, 511, 516, 521, 526, 531, 536, 
  541, 546, 551, 556, 561, 566, 571, 576, 581, 586, 591, 596, 601, 606, 611, 
  616, 621, 626, 631, 636, 641, 646, 651, 656, 661, 666, 671, 676, 681, 686, 
  691, 696, 701, 706, 711, 716, 721, 726, 731, 736, 741, 746, 751, 756, 761, 
  766, 771, 776, 781, 786, 791, 796, 801, 806, 811, 816, 821, 826, 831, 836, 
  841, 846, 851, 856, 861, 866, 871, 876, 881, 886, 891, 896, 901, 906, 911, 
  916, 921, 926, 931, 936, 941, 946, 951, 956, 961, 966, 971, 976, 981, 986, 
  991, 996
];


module.exports = { nomesSimples, nomesCompostos, nomes, numeros };